[build]
  command = "pnpm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NEXT_PUBLIC_API_BASE_URL = "https://www.alphavantage.co/query"
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

# Note: Do NOT put your actual API key in this file
# Add it through the Netlify UI instead 

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Function-specific settings
[functions."*"]
  external_node_modules = ["@google/generative-ai"]
  included_files = []

[functions.config]
  timeout_seconds = 30 